In [382]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier

In [383]:
df = pd.read_csv("C:\\Users\\chase\\Documents\\GitHub\\ProjetoFinalTA\\df_final.csv")
df_test = pd.read_csv("C:\\Users\\chase\\Documents\\GitHub\\ProjetoFinalTA\\df_teste_final.csv")
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,41.0,management,single,tertiary,0,4522.0,0,0,cellular,28,aug,55,1.0,0,0,unknown,0
1,42.0,blue-collar,married,primary,1,398.0,1,0,unknown,16,may,251,4.0,0,0,unknown,0
2,26.0,student,single,secondary,0,706.0,0,0,unknown,8,oct,118,1.0,1,0,other,0
3,54.0,management,married,tertiary,0,0.0,0,1,cellular,19,nov,307,3.0,0,0,unknown,0
4,43.0,self-employed,married,secondary,0,918.0,1,0,unknown,6,may,193,1.0,0,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38973,43.0,management,married,tertiary,0,13851.0,1,0,cellular,21,nov,259,1.0,0,0,unknown,0
38974,34.0,blue-collar,married,primary,0,357.0,1,0,unknown,14,may,197,2.0,0,0,unknown,0
38975,30.0,management,single,tertiary,0,4889.0,0,0,cellular,11,aug,545,2.0,0,0,unknown,1
38976,40.0,self-employed,married,tertiary,0,271.0,1,0,cellular,21,nov,124,3.0,1,0,failure,0
38977,60.0,housemaid,married,tertiary,0,443.0,0,0,unknown,5,jun,60,1.0,0,0,unknown,0

###Tratando o df

In [384]:
#preparando o datasset para utilizar knn
# df = df.drop('poutcome', axis=1)
# df = df[df['poutcome'] != 'unknown']
# # df = df[df['poutcome'] != 'other']
# df = df[df['contact'] != 'unknown']
# df = df[df['job'] != 'unknown']
# df = df[df['education'] != 'unknown']
df = df.dropna()

In [385]:
#transformando dados categÃ³ricos com get_dummies
df = pd.get_dummies(df)
df_test = pd.get_dummies(df_test)
df

,age,default,balance,housing,loan,day,duration,campaign,pdays,previous,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,41.0,0,4522.0,0,0,28,55,1.0,0,0,...,False,False,False,False,False,False,False,False,False,True
1,42.0,1,398.0,1,0,16,251,4.0,0,0,...,False,False,True,False,False,False,False,False,False,True
2,26.0,0,706.0,0,0,8,118,1.0,1,0,...,False,False,False,False,True,False,False,True,False,False
3,54.0,0,0.0,0,1,19,307,3.0,0,0,...,False,False,False,True,False,False,False,False,False,True
4,43.0,0,918.0,1,0,6,193,1.0,0,0,...,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38973,43.0,0,13851.0,1,0,21,259,1.0,0,0,...,False,False,False,True,False,False,False,False,False,True
38974,34.0,0,357.0,1,0,14,197,2.0,0,0,...,False,False,True,False,False,False,False,False,False,True
38975,30.0,0,4889.0,0,0,11,545,2.0,0,0,...,False,False,False,False,False,False,False,False,False,True
38976,40.0,0,271.0,1,0,21,124,3.0,1,0,...,False,False,False,True,False,False,True,False,False,False
38977,60.0,0,443.0,0,0,5,60,1.0,0,0,...,True,False,False,False,False,False,False,False,False,True

###Colocando o df na escala correta

In [386]:
#botando o dataframe na escala para o knn
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_data
df = pd.DataFrame(scaled_data, columns = df.columns)
df.head()

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df_test)
scaled_data
df_test = pd.DataFrame(scaled_data, columns = df_test.columns)
df_test.head()

,age,default,balance,housing,loan,day,duration,campaign,pdays,previous,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,0.126761,0.0,0.027183,0.0,1.0,0.933333,0.002559,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.274648,0.0,0.044486,1.0,0.0,0.033333,0.002119,0.032258,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.190141,0.0,0.061680,0.0,0.0,0.366667,0.003066,0.032258,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.323944,0.0,0.044964,0.0,0.0,0.966667,0.001413,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.133803,0.0,0.025723,1.0,0.0,0.666667,0.001959,0.016129,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

###Treinando o modelo

In [387]:
#separando o df
X = df.drop('y', axis = 1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

knn = KNeighborsClassifier(n_neighbors = 20)
knn.fit(X_train, y_train)
knn.score(X_test , y_test)

0.898876404494382

In [388]:
y_pred = knn.predict(df_test)
df_resultado = pd.read_csv("C:\\Users\\chase\\Documents\\GitHub\\ProjetoFinalTA\\raw_data\\bank_test.csv")

In [389]:
df_resultado = pd.DataFrame({'id': np.array(df_resultado['id']), "y": y_pred})
df_resultado.index = df_resultado["id"]
df_resultado = df_resultado.drop('id',axis=1)

In [390]:
df_resultado.to_csv("C:\\Users\\chase\\Documents\\GitHub\\ProjetoFinalTA\\target.csv")